// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HandleTaskReq struct {
	TaskCode             int32      `protobuf:"varint,1,opt,name=TaskCode,proto3" json:"TaskCode,omitempty"`
	EmailInfo            *EmailInfo `protobuf:"bytes,2,opt,name=EmailInfo,proto3" json:"EmailInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HandleTaskReq) Reset()         { *m = HandleTaskReq{} }
func (m *HandleTaskReq) String() string { return proto.CompactTextString(m) }
func (*HandleTaskReq) ProtoMessage()    {}
func (*HandleTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *HandleTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskReq.Unmarshal(m, b)
}
func (m *HandleTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskReq.Marshal(b, m, deterministic)
}
func (m *HandleTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskReq.Merge(m, src)
}
func (m *HandleTaskReq) XXX_Size() int {
	return xxx_messageInfo_HandleTaskReq.Size(m)
}
func (m *HandleTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskReq proto.InternalMessageInfo

func (m *HandleTaskReq) GetTaskCode() int32 {
	if m != nil {
		return m.TaskCode
	}
	return 0
}

func (m *HandleTaskReq) GetEmailInfo() *EmailInfo {
	if m != nil {
		return m.EmailInfo
	}
	return nil
}

type HandleTaskResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleTaskResp) Reset()         { *m = HandleTaskResp{} }
func (m *HandleTaskResp) String() string { return proto.CompactTextString(m) }
func (*HandleTaskResp) ProtoMessage()    {}
func (*HandleTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *HandleTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskResp.Unmarshal(m, b)
}
func (m *HandleTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskResp.Marshal(b, m, deterministic)
}
func (m *HandleTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskResp.Merge(m, src)
}
func (m *HandleTaskResp) XXX_Size() int {
	return xxx_messageInfo_HandleTaskResp.Size(m)
}
func (m *HandleTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskResp proto.InternalMessageInfo

func (m *HandleTaskResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HandleTaskResp) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type EmailInfo struct {
	Ac                   string   `protobuf:"bytes,1,opt,name=Ac,proto3" json:"Ac,omitempty"`
	Ps                   string   `protobuf:"bytes,2,opt,name=Ps,proto3" json:"Ps,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`
	Receive              string   `protobuf:"bytes,4,opt,name=Receive,proto3" json:"Receive,omitempty"`
	ModalIndex           string   `protobuf:"bytes,5,opt,name=ModalIndex,proto3" json:"ModalIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailInfo) Reset()         { *m = EmailInfo{} }
func (m *EmailInfo) String() string { return proto.CompactTextString(m) }
func (*EmailInfo) ProtoMessage()    {}
func (*EmailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *EmailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailInfo.Unmarshal(m, b)
}
func (m *EmailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailInfo.Marshal(b, m, deterministic)
}
func (m *EmailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailInfo.Merge(m, src)
}
func (m *EmailInfo) XXX_Size() int {
	return xxx_messageInfo_EmailInfo.Size(m)
}
func (m *EmailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EmailInfo proto.InternalMessageInfo

func (m *EmailInfo) GetAc() string {
	if m != nil {
		return m.Ac
	}
	return ""
}

func (m *EmailInfo) GetPs() string {
	if m != nil {
		return m.Ps
	}
	return ""
}

func (m *EmailInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EmailInfo) GetReceive() string {
	if m != nil {
		return m.Receive
	}
	return ""
}

func (m *EmailInfo) GetModalIndex() string {
	if m != nil {
		return m.ModalIndex
	}
	return ""
}

func init() {
	proto.RegisterType((*HandleTaskReq)(nil), "grpc.HandleTaskReq")
	proto.RegisterType((*HandleTaskResp)(nil), "grpc.HandleTaskResp")
	proto.RegisterType((*EmailInfo)(nil), "grpc.EmailInfo")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xc3, 0x40,
	0x0c, 0x46, 0x49, 0x48, 0x81, 0x18, 0x51, 0x24, 0xc3, 0x70, 0xea, 0x80, 0xaa, 0x4c, 0x5d, 0xc8,
	0x50, 0x26, 0x36, 0x02, 0xaa, 0xd4, 0x0e, 0x95, 0xaa, 0x13, 0x13, 0xdb, 0x91, 0x1c, 0x55, 0x95,
	0x10, 0x87, 0x73, 0x84, 0xe0, 0xdf, 0xa3, 0x33, 0x90, 0x1e, 0x62, 0xf3, 0xf7, 0xee, 0xfc, 0x2c,
	0x1b, 0xa0, 0x37, 0x5c, 0xe7, 0x9d, 0xa3, 0x9e, 0x30, 0xd9, 0xba, 0xae, 0xcc, 0x9e, 0xe0, 0x6c,
	0x69, 0xda, 0xaa, 0xb1, 0x8f, 0x86, 0x6b, 0x6d, 0xdf, 0x70, 0x02, 0x27, 0xbe, 0x7c, 0xa0, 0xca,
	0xaa, 0x68, 0x1a, 0xcd, 0x46, 0x7a, 0xc8, 0x78, 0x0d, 0xe9, 0xe2, 0xd5, 0xec, 0x9a, 0x55, 0xfb,
	0x42, 0x2a, 0x9e, 0x46, 0xb3, 0xd3, 0xf9, 0x79, 0xee, 0x35, 0xf9, 0x80, 0xf5, 0xfe, 0x47, 0x76,
	0x07, 0xe3, 0xd0, 0xcd, 0x1d, 0x22, 0x24, 0x81, 0x58, 0x6a, 0x3f, 0x70, 0xe1, 0x1c, 0xb9, 0x35,
	0x6f, 0xc5, 0x99, 0xea, 0x21, 0x67, 0x9f, 0xc1, 0x40, 0x1c, 0x43, 0x5c, 0x94, 0xd2, 0x9a, 0xea,
	0xb8, 0x28, 0x7d, 0xde, 0xf0, 0x4f, 0x4b, 0xbc, 0x61, 0x2f, 0x5f, 0x12, 0xf7, 0xea, 0x50, 0x88,
	0xd4, 0xa8, 0xe0, 0x58, 0xdb, 0xd2, 0xee, 0xde, 0xad, 0x4a, 0x04, 0xff, 0x46, 0xbc, 0x02, 0x58,
	0x53, 0x65, 0x9a, 0x55, 0x5b, 0xd9, 0x0f, 0x35, 0x92, 0xc7, 0x80, 0xcc, 0x0b, 0x48, 0xee, 0x89,
	0x6a, 0xbc, 0x05, 0xd8, 0x2f, 0x81, 0x17, 0xdf, 0xeb, 0xfe, 0x39, 0xd9, 0xe4, 0xf2, 0x3f, 0xe4,
	0x2e, 0x3b, 0x78, 0x3e, 0x92, 0x43, 0xdf, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x15, 0xdf, 0x51,
	0xeb, 0x76, 0x01, 0x00, 0x00,
}
